### ISSUE TITLE
Hover tooltips don't disappear

### ISSUE THREAD

**Issue by matthewmichihara** [ballerina-platform/lsp4intellij#100]
**Description:**
I think there are two related issues here:
1. Long hover text does not wrap. For example, I expected the text in the following gif to wrap to a few lines and not extend beyond the editor window.
2. When hover text extends beyond the editor window, it doesn't clear itself on mouse movement.

![out](https://user-images.githubusercontent.com/79073/59880478-1e4af480-937b-11e9-9699-a2b2c226d8c2.gif)

**Suggested Labels:**
Bug

**Affected Product Version:**
`com.github.ballerina-platform:lsp4intellij:Tag:0.91.0`

**OS, DB, other environment details and versions:**
OS: macOS Mojave
IntelliJ: 2019.1.2
JDK: 1.8

**Comment by NipunaRanasinghe** [comment]
@matthewmichihara Thanks for reporting this... As per the Gitter discussion, I'll have a look on implementing the hover support using `DocumentationProvider` or else will do a patch for this one. :)
