### ISSUE TITLE
[question / feature request] Completion snippet support

### ISSUE THREAD

**Issue by matthewmichihara** [ballerina-platform/lsp4intellij#101]
As part of the [LSP spec](https://microsoft.github.io/language-server-protocol/specification#initialize), clients can declare the capability for `snippetSupport` in code completions.

Description from the docs:
```
The client supports snippets as insert text.
A snippet can define tab stops and placeholders with `$1`, `$2`
and `${3:foo}`. `$0` defines the final tab stop, it defaults to
the end of the snippet. Placeholders with equal identifiers are linked,
that is typing in one will update others too.
```

lsp4intellij currently has this disabled:
https://github.com/ballerina-platform/lsp4intellij/blob/master/src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java#L520

This seems like something that could be implemented using IntelliJ live templates with variables. Has there been any thought about adding support for this?

**Comment by NipunaRanasinghe** [comment]
@matthewmichihara  Thanks for bringing this up!  This is already in the roadmap and hopefully will be able to start working on this in the next few weeks, after adding signature help. :)
