### ISSUE TITLE
Quick Documentation provider is not working

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/lsp4intellij#103]
**Description:**
$subject.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by kevinvdbekerom** [comment]
Is there any progress on this issue? For me it is not working.

**OS, DB, other environment details and versions:**
Windows 10
IntelliJ2020.2 Community Edition
LSP Support plugin v 1.6.1

**Steps to reproduce:**

1. Create new Xtext project with LSP support.
2. Build jar with gradle
3. Add jar in intelliJ
4. Add some code, and hover on a language element.

![image](https://user-images.githubusercontent.com/10022627/90519619-902df200-e168-11ea-9659-8f9aa8c15f21.png)

As you can see, the provided documentation is empty.
