### ISSUE TITLE
didChangeWatchedFiles is called for non-language files

### ISSUE THREAD

**Issue by dinvlad** [ballerina-platform/lsp4intellij#106]
**Description:**

For some reason, my language server (based on [pygls](https://pygls.readthedocs.io/en/latest/)) receives `workspace/didChangeWatchedFiles` even for the files that don't match the language extension.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
`0.91.0`

**OS, DB, other environment details and versions:**    
macOS 10.13.6
IntelliJ Community 2019.1.3

**Steps to reproduce:**
1. Open a project with both the files of interest and others.
2. Change a language file.
3. Change an unrelated file.
4. Observe that the server log (`pygls.log` in my case) contains `didChangeWatchedFiles` events for both file types.

**Related Issues:**

**Comment by NipunaRanasinghe** [comment]
Thanks you so much bringing this up as it seems like we've missed the guarding for unrelated files in file event handling, which might also causes a performance hit. I've refactored the client to filter-out files which do no have any language server definitions attached.

**Comment by dinvlad** [comment]
Perfect, thanks!
