### ISSUE TITLE
Do we have performance test now?

### ISSUE THREAD

**Issue by MagicRUBICK** [ballerina-platform/lsp4intellij#153]
eg: a switch or path configuration to export the lsp4intellij **client** and **server** performance.

**Comment by NipunaRanasinghe** [comment]
@MagicRUBICK Sorry we don't have any implementation for the $subject. You have any suggestions on this? and any contributions will be more than appreciated :)

**Comment by anupama-pathirage** [comment]
Closing the issue based on the above answer. @MagicRUBICK please feel free to re-open the issue if you have suggestions.
