### ISSUE TITLE
[Annotation] in some situation, the diagnostic annotation maybe show in wrong place

### ISSUE THREAD

**Issue by MagicRUBICK** [ballerina-platform/lsp4intellij#163]
**Description:**
in some low-profile computer, the diagnostic annotation would show in wrong place after reformat code.

![image](https://user-images.githubusercontent.com/22075197/69596456-9b227e80-103d-11ea-80e7-8370fe1c0d89.png)

And I tried to replace the range-based annotation with PsiElement-based annotation(we implemented a PSI tree for our language), the issue was disappear, do you think it's good idea?

**Comment by NipunaRanasinghe** [comment]
@MagicRUBICK As far as I understand, the particular language server is responsible of sending a new diagnostics map with the updated ranges after formatting a source file. Also, the current works is also valid for the plugins which have not implemented the PSI tree, IMO its better to stick with the current approach :) WDYT?
