### ISSUE TITLE
[SemanticHighlighting][Beta] We implement this beta feature, do you want it?

### ISSUE THREAD

**Issue by MagicRUBICK** [ballerina-platform/lsp4intellij#164]
**Description:**
the proposal: https://github.com/microsoft/language-server-protocol/issues/18

**Comment by NipunaRanasinghe** [comment]
@MagicRUBICK yes please! :) It would be great to have this feature implemented.

**Comment by tyranteon** [comment]
I'd definitely need this feature as well.

**Comment by swissiety** [comment]
SemanticHighlighting was not an official extension. An equivalent will be SemanticToken in LSP 3.16.

**Comment by swissiety** [comment]
I guess we can close this wooing issue now as LSP 3.16 is officially published and the referenced PR is closed.
