### ISSUE TITLE
[question] Calling LS methods directly

### ISSUE THREAD

**Issue by nixel2007** [ballerina-platform/lsp4intellij#18]
I have a LS with some stored `configuration`. I want to update its configuration from IDEA via some button in settings window. 
Is there any method to get connected language-server and fire `workspace/didChangeConfiguration` event from my plugin?

**Comment by NipunaRanasinghe** [comment]
I believe it should be exposed via this client API. I'll have a look :)

**Comment by DanielFGA** [comment]
Hello,
I have a similar question. I want to build a tool window in my plugin, where I display the diagnostics. Is there a way to get current diagnostics from the LS into my plugin? I already saw that the EditorEventManager has a list with the current diagnostics, but I can´t figure out, how to get them.

**Comment by NipunaRanasinghe** [comment]
@nixel2007 I believe you can directly use `IntelliJLanguageClient.didChangeConfiguration()` API for your purpose. It's available in the latest client release version. Please feel free to re-open if you need any further assistance on this

**Comment by nixel2007** [comment]
I'm happy to see you back on track :)

**Comment by NipunaRanasinghe** [comment]
> I'm happy to see you back on track :)

Happy to see you too! :)
