### ISSUE TITLE
[plugin compat] Internal API usage

### ISSUE THREAD

**Issue by gayanper** [ballerina-platform/lsp4intellij#189]
IntelliJ IDEA Ultimate IU-201.7846.29 Compatible.

1 internal API usage
  uses internal API, which is not supposed to be used outside of the IntelliJ Platform.

Internal method usage:
StatusBar.removeWidget(String)

**Comment by NipunaRanasinghe** [comment]
> To fix these issue we need to switch to new alternative statusbar widget API or we should consider removing the statusbar widget. Because when running multiple LSP implementation this clutters the status bar. WDYT @NipunaRanasinghe ?

As far as I remember I also tried to find a proper fix for status icon cluttering issue but got no luck. Did you find any alternative status bar widget API? If not, maybe we can think of alternative ways to indicate the stats like connection status, and connected files, timeouts, etc.

**Comment by gayanper** [comment]
The recommendation is to use StatusBarWidgetFactory. But I didn't look at it much closer since that API is not available in 2017.

**Comment by NipunaRanasinghe** [comment]
> The recommendation is to use StatusBarWidgetFactory. But I didn't look at it much closer since that API is not available in 2017.

As of now we have to bump the minimum version anyway, I think its high-time to migrate to the recommended API. Lets keep this is in our roadmap.

**Comment by NipunaRanasinghe** [comment]
Closing as addressed with https://github.com/intellij-purescript/intellij-purescript/issues/78 and https://github.com/ballerina-platform/lsp4intellij/pull/251
