### ISSUE TITLE
[plugin compat] usages of scheduled for removal API

### ISSUE THREAD

**Issue by gayanper** [ballerina-platform/lsp4intellij#190]
4 usages of scheduled for removal API

StatusBarWidget.PlatformType (2) (scheduled for removal in 2020.2)
  Deprecated enum StatusBarWidget.PlatformType is referenced in 
    LSPServerStatusWidget.getPresentation(...). This enum will be removed in 2020.2
  Deprecated enum StatusBarWidget.PlatformType is referenced in 
    LSPServerStatusWidget.getPresentation(...). This enum will be removed in 2020.2

Scheduled for removal methods usages (2)
  StatusBar.addWidget(StatusBarWidget, String) (1) (scheduled for removal in a future release)
  StatusBarWidget.getPresentation(...) (1) (scheduled for removal in 2020.2)

**Comment by gayanper** [comment]
```StatusBar.addWidget(StatusBarWidget, String) (1) (scheduled for removal in a future release)``` can wait a little bit more since it doesn't have a removal date yet and the alternative API is only introduced in 2020. @NipunaRanasinghe should we still need to keep the minimum IJ version on 2017 for this library ?

**Comment by NipunaRanasinghe** [comment]
>  @NipunaRanasinghe should we still need to keep the minimum IJ version on 2017 for this library ?

@gayanper Not really :) The goal is to keep the IDEA compatibility range of the library as wider as possible. But with the continuous platform API changes its being a difficult goal and now we are on 2020.x versions, I also don't think there are many users for 2017.x versions.
So I think it'll be good enough if we can keep the support for 2019.x - 2020.x versions at this points. WDYT?

**Comment by NipunaRanasinghe** [comment]
> StatusBar.addWidget(StatusBarWidget, String) (1) (scheduled for removal in a future release) can wait a little bit more since it doesn't have a removal date yet and the alternative API is only introduced in 2020.

yeah if the alternative API is introduced only in 2020.1 platform, it will make the library incompatible even for 2019.x versions. I also think we can wait as they still don't have a removal date for it.

**Comment by gayanper** [comment]
> > @NipunaRanasinghe should we still need to keep the minimum IJ version on 2017 for this library ?
> 
> @gayanper Not really :) The goal is to keep the IDEA compatibility range of the library as wider as possible. But with the continuous platform API changes its being a difficult goal and now we are on 2020.x versions, I also don't think there are many users for 2017.x versions.
> So I think it'll be good enough if we can keep the support for 2019.x - 2020.x versions at this points. WDYT?

Yes, I think that's a good idea.

**Comment by Neppord** [comment]
Hey, i started to use this library in the purescript plugin https://github.com/intellij-purescript/intellij-purescript https://plugins.jetbrains.com/plugin/9738-purescript .

The compatibility verification is now complaining about these errors. Is there any way for me to help out? Where should i start, is there anyone who could take some time to pair program or ensemble-work with me?

**Comment by Neppord** [comment]
the worst offender is probably this error

> Internal method StatusBar.removeWidget(String) is invoked in LSPServerStatusWidget.lambda$dispose$0(StatusBar). This method is marked with @ApiStatus.Internal annotation and indicates that the method is not supposed to be used in client code.

**Comment by nixel2007** [comment]
I've removed internal call in https://github.com/nixel2007/lsp4intellij/commit/c3b4f80462daa6e84354d935e7b99a26c704e4d5 (not tested yet) but it looks like we need to rewrite all widget-related stuff to StatusBarWidgetFactory implementation, cause many of statusbar/widget methods used in LSPServerStatusWidget and around it are deprecated and suggested to removal.

**Comment by nixel2007** [comment]
https://github.com/jonathanlermitage/intellij-battery-status-plugin deservses attention as plugin that uses new statusbar/widget api.

**Comment by Trias** [comment]
I'm looking into this right now and it seems that with the new API, the statusbar widget is created before any components init. meaning we can't display any meaningful information until our component inits. Does anyone have an idea on how to solve this?
