### ISSUE TITLE
LSPPOS outofbounds

### ISSUE THREAD

**Issue by carymrobbins** [ballerina-platform/lsp4intellij#198]
I see a ton of these warnings often -

```
WARN - p4intellij.utils.DocumentUtils - LSPPOS outofbounds : Position [
  line = 24
  character = 9
] line : foo = 2.5 column : 9 offset : 702 
```

I'm not entirely sure what's causing this, just want to document it here for now.

**Comment by kdiehl** [comment]
I also often come across these LSPPOS outofbounds errors, especially at the end of documents. However, I can not clearly say if it's my fault.

**Comment by NipunaRanasinghe** [comment]
@carymrobbins @kdiehl Thanks for reporting. I'll see whether I can reproduce this against our language server.

**Comment by swissiety** [comment]
first guess: LSP & intelliJ are starting line numbers zero based. Maybe its an off by one bug on the input side e.g. antlr starts line numbers one-based but the chararacter in line zero based (learned that from experience ;) ).

Additionally: "The offsets are based on a UTF-16 string representation. So a string of the form a𐐀b the character offset of the character a is 0, the character offset of 𐐀 is 1 and the character offset of b is 3 since 𐐀 is represented using two code units in UTF-16.". And im afraid (didnt checked it yet) this is not implemeneted as described in `DocumentUtils.LSPPosToOffset(..)`.

**Comment by Trias** [comment]
I've looked into this and as of my understanding it does not indicate a problem in the library. However i think we should remove /downgrade the logging as it is a common occurence and may bury more serious logs.

There are 2 conditions where this problem can arise:
1. Language server send a Position which spans to the end of line. In this case the soec says that the position should wrap to the 0th character of the next line. However it also says that extra characters in a position default to the end of line. So Language server do not really need to implement the wrapping. https://microsoft.github.io/language-server-protocol/specification#position & https://microsoft.github.io/language-server-protocol/specification#range 
2. A validation is send from the language server on an outdated document version. We currently have no mechanism to translate those to the current version and i think it would be a big effort trying to do so. This can also lead to diagnostics in the wrong place. However they should be cleaned up once the language server sends the validation for the current document version.

In my understanding these conditions do not warrant a "warning" but rather an "debug" or "info"-log, however  there might be other cases where this condition actually does indicate a problem in the language server or in the library.

**Comment by nixel2007** [comment]
>  We currently have no mechanism to translate those to the current version and i think it would be a big effort trying to do so.

my 2cents. 3.15 spec adds `version` field `PublishDiagnosticsParams` (`publishDagnostics` notification) plus adds `versionSupport` to `PublishDiagnosticsClientCapabilities`.  

versionSupport is described as:
```typescript
	/**
	 * Whether the client interprets the version property of the
	 * `textDocument/publishDiagnostics` notification's parameter.
	 *
	 * @since 3.15.0
	 */
	versionSupport?: boolean;
```

so client (lsp4intellij) *may* drop recieved diagnostics from incorrect (not last) version of document.

**Comment by swissiety** [comment]
Additionally there is a bug in the logic - I'll create a PR for this after christmas as im currently occupied with finishing my thesis.

**Comment by swissiety** [comment]
@Trias do you have the line for the thing with the 0th char-> end of previous line from spec at hand? cant find it currently but im sure i've read it, too

**Comment by Trias** [comment]
@swissiety It's in the link i posted: 
<blockquote>If you want to specify a range that contains a line including the line ending character(s) then use an end position denoting the start of the next line. For example:

```
{
    start: { line: 5, character: 23 },
    end : { line: 6, character: 0 }
}
```
</blockquote>
[link](https://microsoft.github.io/language-server-protocol/specification#range)

**Comment by swissiety** [comment]
thx! i guess it was too late yesterday.
