### ISSUE TITLE
Annotation Deprecation

### ISSUE THREAD

**Issue by carymrobbins** [ballerina-platform/lsp4intellij#200]
There are multiple usages of the deprecated annotation API, namely the use of `AnnotationHolder.create{Info,Warning,Error}Annotation()` which returns an `Annotation`. These should be replaced with `AnnotationHolder.newAnnotation()` which returns an `AnnotationBuilder`. With the latter, you never get handed an `Annotation`; instead, you build an annotation via the methods on `AnnotationBuilder` and finally call `.create()` which returns `void()` to display the annotation.

Currently, we have two classes which use these deprecated methods, `LSPAnnotator` and `EditorEventManager`.

I think the following is a start towards updating `LSPAnnotator.createAnnotations()`.

```java
    @Nullable
    protected AnnotationBuilder createAnnotationBuilder(Editor editor, AnnotationHolder holder, Diagnostic diagnostic) {
        final int start = DocumentUtils.LSPPosToOffset(editor, diagnostic.getRange().getStart());
        final int end = DocumentUtils.LSPPosToOffset(editor, diagnostic.getRange().getEnd());
        if (start >= end) {
            return null;
        }
        final TextRange textRange = new TextRange(start, end);
        return
          holder
            .newAnnotation(getHighlightSeverity(diagnostic), diagnostic.getMessage())
            .range(textRange);
    }

    private HighlightSeverity getHighlightSeverity(Diagnostic diagnostic) {
        switch (diagnostic.getSeverity()) {
            case Error:
                return HighlightSeverity.ERROR;
            case Warning:
                return HighlightSeverity.WARNING;
            case Information:
                return HighlightSeverity.INFORMATION;
            default:
                return HighlightSeverity.WEAK_WARNING;
        }
    }

    private void createAnnotations(AnnotationHolder holder, EditorEventManager eventManager) {
        final List<Diagnostic> diagnostics = eventManager.getDiagnostics();
        final Editor editor = eventManager.editor;

        diagnostics.forEach(d -> {
            AnnotationBuilder annotationBuilder = createAnnotationBuilder(editor, holder, d);
            if (annotationBuilder != null) {
                annotationBuilder.create();
            }
        });

        eventManager.setAnonHolder(holder);
    }
```

I'm not entirely sure if we need to retain the `AnnotationBuilder`s in a `List` as we do with the `Annotation`s currently, as I don't entirely understand what the `isCodeActionSyncRequired` case is for or how it is supposed to work. This also seems tricky to deal with in `EventEditorManager.requestAndShowCodeActions()` as it completely relies on having `Annotation`s which contain source positions whereas `AnnotationBuilder`s do not.

**Comment by NipunaRanasinghe** [comment]
> I'm not entirely sure if we need to retain the AnnotationBuilders in a List as we do with the Annotations currently, as I don't entirely understand what the isCodeActionSyncRequired case is for or how it is supposed to work. This also seems tricky to deal with in EventEditorManager.requestAndShowCodeActions() as it completely relies on having Annotations which contain source positions whereas AnnotationBuilders do not.

@carymrobbins What you are saying is correct and that complexity comes when providing the support for line based code actions (where we have to fetch code actions based on the cursor position changes). So we'll need to carefully have a look how we can replace the exiting `AnnotationHolder` usages with `AnnotationBuilder` impmlementation.
