### ISSUE TITLE
Support to start language server without a Editor Open

### ISSUE THREAD

**Issue by gayanper** [ballerina-platform/lsp4intellij#203]
**Proposal** 
I would like to bring a proposal for starting up a language server without opening a file. The consumer who wants to start the language server should be started.

**Usecase**
Today to see all symbols, one should open a file to get the language server started. This is really annoying to open a file just to list all symbols.

For example vscode starts the java language server when a java project is opened. This enables the user to search symbols and navigate to them without opening a random file.

**Solutions**
1. Since we keep track of the language ids we could let the consumer to start the server by a given language id
2. If language ids are not used the extension can be used.

Once the server is started we should reuse the server for files that are opened as well.

@NipunaRanasinghe WDYT ?

**Comment by NipunaRanasinghe** [comment]
@gayanper If I understand your requirement correctly, what you are proposing is a public API to dynamically start/stop language server(s). I also do see that as a valid requirement.

**Comment by gayanper** [comment]
@NipunaRanasinghe yes. Vscode code has this behavior where you can provide a workspace predicate to startup a extension. But I don’t this we need to go that route. A public API might be sufficient
