### ISSUE TITLE
Definition request doesn't adhere to spec

### ISSUE THREAD

**Issue by BinaryFissionGames** [ballerina-platform/lsp4intellij#207]
**Description:**
The go to definition request will error out if a single Location (not wrapped in a list) is returned. However, the specification says that this is a valid shape of the return message.

See: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_definition

**Suggested Labels:**
Type/Bug

**Suggested Assignees:**

**Affected Product Version:**
0.94.2

**OS, DB, other environment details and versions:**    
Windows 10, IntelliJ 2020.1.1, https://github.com/Denu8thell/intellij-prisma/tree/prisma-language-server-integration

**Steps to reproduce:**
Pull, compile, and run the above plugin, attempt to find a definition (ctrl+click), the server returns a payload like this:
```
{
  "jsonrpc": "2.0",
  "id": "3",
  "result": {
    "uri": "file:///C:/Users/Brandon/IdeaProjects/testPlugin/src/test.prisma",
    "range": {
      "start": {
        "line": 87,
        "character": 0
      },
      "end": {
        "line": 92,
        "character": 1
      }
    }
  }
}
```
, which crashes the server.

**Comment by NipunaRanasinghe** [comment]
@BinaryFissionGames thanks for reporting and we'll try to provide a proper fix with the next release

**Comment by BinaryFissionGames** [comment]
I looked into this a bit and found that it was an issue in lsp4j. I opened an issue with them [here](https://github.com/eclipse/lsp4j/issues/435). I'll try to look into a workaround in the meantime, but it might turn out pretty hacky, unfortunately....
