### ISSUE TITLE
Formatting request doesn't provide indent amount/tabsize

### ISSUE THREAD

**Issue by BinaryFissionGames** [ballerina-platform/lsp4intellij#208]
**Description:**
Formatting request doesn't provide indent amount/tabsize when making a request, which is required by the spec.

See: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_formatting

**Suggested Labels:**
Type/Bug

**Suggested Assignees:**

**Affected Product Version:**
0.94.2

**OS, DB, other environment details and versions:**    
Windows 10, IntelliJ 2020.1.1, https://github.com/Denu8thell/intellij-prisma/tree/prisma-language-server-integration

**Steps to reproduce:**
Pull, compile, and run the above plugin, attempt to format, which does nothing (the language server fails to format, and fails silently due to a different bug).

**Comment by NipunaRanasinghe** [comment]
@BinaryFissionGames As you've mentioned, In the spec they've not mentioned whether the `FormattingOptions` can be optional, but lsp4j has allowed the default public no-arg constructor option when creating `FormattingOptions (which could be a possible spec deviation), which makes the client to provide the formatting options without the indent/tabize properties. Anyway I'm +1 to add the support.

**Comment by BinaryFissionGames** [comment]
I was wondering how we'd like to implement this? 

My thought was to have an interface that has a single method that returns a FormattingOptions instance, then have the *ServerDefinition classes take in this interface as an optional parameter. This way it's configurable and up to whoever uses the library whether they want to make this user configurable or not. 

Downside is that if it's not provided, it'll have to revert to the current behavior if one is not provided, but maybe that's alright? Or would we prefer if this is required as to adhere to the spec?

**Comment by swissiety** [comment]
> @BinaryFissionGames As you've mentioned, In the spec they've not mentioned whether the `FormattingOptions` can be optional, but lsp4j has allowed the default public no-arg constructor option when creating a `FormattingOptions` instance (which could be a possible spec deviation), which makes the client to provide the formatting options without the indent/tabize properties. Anyway I'm +1 for adding indent/tabize properties in the request.

lsp4j just provides the datastructures and the communication channel/serialization; it doesnt validate what you are sending except from providing the basic nesting of the defined datastructures! If i remember it correctly the deviation with the zero parameter constructor has sth to do with eclipse Xtend, so we need to add  the missing values via setter.

Tabsize: like in `DocumentUtils.LSPPosToOffset(..)`.
Indent Amount: I suggest this would be the amount of tabs which are currently at the start of the selection for range formatting request (see calculation in `DocumentUtils.LSPPosToOffset(..)`) and zero for the whole file in document formatting request.
