### ISSUE TITLE
Message is logged as unknown type when it shouldn't be

### ISSUE THREAD

**Issue by BinaryFissionGames** [ballerina-platform/lsp4intellij#209]
**Description:**

In DefaultLanguageClient.logMessage, it appears an "else" is missing, making any message types that aren't MessageType.Log fail

**Suggested Labels:**

Type/Bug

**Suggested Assignees:**

**Affected Product Version:**
0.94.2
**OS, DB, other environment details and versions:**    
Windows 10, IntelliJ 2020.1.1

**Steps to reproduce:**
Trigger a logMessage request for any language server that is not of type Log. Inspect logs and see it has been logged twice. 

**Related Issues:**

**Comment by NipunaRanasinghe** [comment]
@BinaryFissionGames I just had a look and as you said the logic should be corrected using an "else if" block. +1 for the change.
