### ISSUE TITLE
showMessageRequest fail if no actions are set

### ISSUE THREAD

**Issue by BinaryFissionGames** [ballerina-platform/lsp4intellij#210]
**Description:**

DefaultLanguageClient.showMessageRequest fails and throws an NPE if no actions are send in the request. Such a request is perfectly valid. In this case, the user should be prompted with an "OK" prompt displaying the message.

See interface for ShowMessageRequestParams here: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#window_showMessageRequest

**Suggested Labels:**

Type/Bug

**Suggested Assignees:**

**Affected Product Version:**
0.94.2

**OS, DB, other environment details and versions:**    
Windows 10, Intellij 2020.1.1

**Steps to reproduce:**
Have the language server send a ShowMessageRequestParams object that does not have any actions. Observe NPE.

**Related Issues:**

**Comment by Denu8thell** [comment]
Just to give more context in general about these past few issues; I've been working on integrating the [prisma language server](https://github.com/prisma/language-tools/tree/master/packages/language-server) using lsp4intellij. What I have so far (which has all these issues I've posted) is [in this repo](https://github.com/Denu8thell/intellij-prisma/tree/prisma-language-server-integration).

I've spent a while debugging these issues (#207 #208 #209 #210) to make sure they weren't bugs on the language server itself, so if you would like me to create the fixes and make pull request(s), I'd be happy to.

Thanks!

**Comment by NipunaRanasinghe** [comment]
> DefaultLanguageClient.showMessageRequest fails and throws an NPE if no actions are send in the request. Such a request is perfectly valid. In this case, the user should be prompted with an "OK" prompt displaying the message.
> 
> See interface for ShowMessageRequestParams here: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#window_showMessageRequest

@BinaryFissionGames Yeah this should be fixed so that the no-action requests can be handled gracefully. +1 for the change.

**Comment by NipunaRanasinghe** [comment]
> Just to give more context in general about these past few issues; I've been working on integrating the [prisma language server](https://github.com/prisma/language-tools/tree/master/packages/language-server) using lsp4intellij. What I have so far (which has all these issues I've posted) is [in this repo](https://github.com/Denu8thell/intellij-prisma/tree/prisma-language-server-integration).
> 
> I've spent a while debugging these issues (#207 #208 #209 #210) to make sure they weren't bugs on the language server itself, so if you would like me to create the fixes and make pull request(s), I'd be happy to.
> 
> Thanks!

@BinaryFissionGames Thanks for your valuable time and effort on this and we are more than happy to have external contributions :slightly_smiling_face: Please let me know if you need any further clarifications.
