### ISSUE TITLE
GotoDefinition does not work on Windows / IntelliJ 2020.2

### ISSUE THREAD

**Issue by Trias** [ballerina-platform/lsp4intellij#212]
**Description:**
As the title says, goto definition does not work on Windows, as the URI ist wrongly resolved. 

From my debugging i found out that the incoming URI is "fixed" to include only 2 slashes instead of 3 (in https://github.com/ballerina-platform/lsp4intellij/blob/master/src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java#L1384). This later leads to "C:\\" being dropped and the path is interpreted as relative instead of absolute. When I remove the call to VfsUtilCore.fixURLforIDEA it works fine on windows.

I can submit a pull request but want to makesure there aren't any other options or compatibility problems that i missed.

**Affected Product Version:**
0.94.2

**OS, DB, other environment details and versions:** 
Windows 10, IntelliJ 2020.2, master branch commit 28a5207

**Steps to reproduce:**
Make a request with an uri as a result on windows (for example a textdocument/definition request)

**Comment by NipunaRanasinghe** [comment]
@Trias Thanks for your observations and please feel free to contribute if you have time :slightly_smiling_face:
