### ISSUE TITLE
editText.range is ignored in completion Requests

### ISSUE THREAD

**Issue by Trias** [ballerina-platform/lsp4intellij#213]
**Description:**
Within completion Responses, "textEdit" provides a "newText" and a "range" property. If textEditexists together with "insertText" we give precedence to editText, as the specs says: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion . however, we do not honor the range provided. This leads to double quotation marks in some cases, and can be very annoying.

Additionally we do not honor variables like "$1" in the snippet syntax. The variable syntax is described here: https://code.visualstudio.com/docs/editor/userdefinedsnippets

**Comment by NipunaRanasinghe** [comment]
@Trias I see that you've already fixed these 2 issues with #214. Thanks for working on this and I'll try to provide a new release with all the recent changes/fixes, as soon as possible.
