### ISSUE TITLE
empty strings are not respected in textEdits

### ISSUE THREAD

**Issue by Trias** [ballerina-platform/lsp4intellij#218]
**Description:**
When supplying an empty string in an textEdit (for example in a completion), the text edit is ignored by lsp4intellij. It is therefore impossible to delete text via a textedit.

Empty strings is specifically prevented by lsp4intellij in https://github.com/ballerina-platform/lsp4intellij/blob/master/src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java#L1132, but i cannot see the reason for it, especially as there is code later on to handle empty strings. In my testing i did not found any problems. Is it safe to remove the check?

**Comment by NipunaRanasinghe** [comment]
@Trias I'm afraid this check could be an LSP violation, as like you mentioned, empty string should be allowed in order to delete text via text edits. Thanks for you observation and feel free to send a PR with the fix :slightly_smiling_face:
