### ISSUE TITLE
CodeActionLiteralSupport and versioning error

### ISSUE THREAD

**Issue by kathrynkodama** [ballerina-platform/lsp4intellij#249]
**Description:**
Add `CodeActionLiteralSupport` for quick-fixes in the [LanguageServerWrapper](https://github.com/ballerina-platform/lsp4intellij/blob/master/src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java#L569):
```java
textDocumentClientCapabilities.getCodeAction().setCodeActionLiteralSupport(new CodeActionLiteralSupportCapabilities(Arrays.asList(new String[] {CodeActionKind.QuickFix}));
```

I also notice an error in the versioning where I continue to see this error when selecting a code action:
`Edit version %d is older than current version %d` from the [EditorEventManager](https://github.com/ballerina-platform/lsp4intellij/blob/master/src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java#L1143). I believe this is due to the versions being updated out of sync in the `documentChanged` method of [DocumentEventManager](https://github.com/ballerina-platform/lsp4intellij/blob/master/src/main/java/org/wso2/lsp4intellij/editor/DocumentEventManager.java#L101). The `VersionedTextDocument` is always one version behind the version in `DocumentEventManager`. Altering the code to the below fixes this error:
```java
changesParams.getTextDocument().setVersion(++version);
```

**Suggested Labels:**
bug, enhancement

**Suggested Assignees:**

**Affected Product Version:**
Using the latest version from the master branch

**OS, DB, other environment details and versions:**    
Mac, IntelliJ IDEA Community Edition 2020.3

**Steps to reproduce:**
1. Enable quick-fix code action literal support in lsp4intellij
2. Attempt a quick-fix 
3. Notice that the code action is not applied because and see the versioning error

**Related Issues:**

**Comment by Trias** [comment]
I agree it should be a precrement. It's interesting that apparently has never caused any problems before.

Would you mind sending a Pull Request? :)

**Comment by kathrynkodama** [comment]
Thank you @Trias, see the linked PR
