### ISSUE TITLE
Diagnostics are not shown if the start and end character offset are the same

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/lsp4intellij#265]
**Description:**
Consider the following scenario,

```
function test() returns {
}
```
In the above, I have a diagnostics at the start of the `{`. For example, my params look as below,

```json
{
   "start":{
      "line":0,
      "character":25
   },
   "end":{
      "line":0,
      "character":25
   }
}
```

**Comment by nixel2007** [comment]
But it has no sense, hasn't it?.. You can't highlight range with 0 length.

**Comment by nadeeshaan** [comment]
@nixel2007 I was thinking if we can provide the same behaviour as in VSCode since VSCode properly provides the diagnostic in this scenario.

**Comment by nixel2007** [comment]
@nadeeshaan could you share a screenshot from vscode with zero-length diagnostic?

**Comment by nadeeshaan** [comment]
@nixel2007 please refer the following,
<img width="458" alt="Screen Shot 2022-03-11 at 5 46 07 PM" src="https://user-images.githubusercontent.com/1329674/157865336-5d5af768-9941-476a-99d9-ede8fc861ac7.png">

**Comment by nixel2007** [comment]
Hm. Interesting. Looks like vscode adds some "virtual" space char for highlighting

**Comment by NipunaRanasinghe** [comment]
Closing as fixed with https://github.com/ballerina-platform/lsp4intellij/pull/354
