### ISSUE TITLE
When can a new version 0.94.3  be released?

### ISSUE THREAD

**Issue by fxsg20151212** [ballerina-platform/lsp4intellij#266]
Hello, Version 0.94.2 is released on March 11, 2020. It's been more than two years since a new version has been released. Can you release a new version recently?Maybe it's called 0.94.3.

![image](https://user-images.githubusercontent.com/16264691/167087618-b4df3b08-7660-4b1c-bab7-d192b4f082da.png)

**Comment by fxsg20151212** [comment]
@matthewmichihara @dinvlad @hevayo @mikesamuel   Please take a look at this question.

**Comment by fxsg20151212** [comment]
@NipunaRanasinghe  Can you help release a new version? I really need a new version, thank you!

**Comment by NipunaRanasinghe** [comment]
@fxsg20151212 We've just released [0.95.0](https://github.com/ballerina-platform/lsp4intellij/releases/tag/0.95.0) version and is available in jitpack. I'll also update the release notes soon.

**Comment by fxsg20151212** [comment]
> @fxsg20151212 We've just released [0.95.0](https://github.com/ballerina-platform/lsp4intellij/releases/tag/0.95.0) version and is available on jitpack. I'll also update the release notes soon.

Thank you so much! I've seen it and I'll be upgrading to the latest version.
