### ISSUE TITLE
Symbols not working

### ISSUE THREAD

**Issue by gayanper** [ballerina-platform/lsp4intellij#27]
When integrating the STS4 Language server, it seems the language server symbols are not shown in IDEA symbol view.

**Comment by NipunaRanasinghe** [comment]
We are planning to add the workspace symbols and renaming support by the next week :)

**Comment by gayanper** [comment]
I just had a look and seems like i can add the symbols support around this weekend, have you already started @NipunaRanasinghe  ?

**Comment by NipunaRanasinghe** [comment]
@gayanper Thats great! :) As I told, I'm still bit busy with the release works and you are welcome to implement the symbols support if you have time for that. If not, I can do it by the early next week.

I'm currently working on Timeouts API and will merge it within this week.

**Comment by gayanper** [comment]
Hmmm i think i implemented the workspace Symbols but seems like the symbols i receive doesn't show up in the UI. i did implemented the symbol contributor as well. How do you debug this library with IDEA ?

**Comment by gayanper** [comment]
Go it working :)

**Comment by gayanper** [comment]
@NipunaRanasinghe Added a https://github.com/ballerina-platform/lsp4intellij/pull/36 with symbol support. If there needs to be changes lets discuss.

**Comment by NipunaRanasinghe** [comment]
Forgive me for the late response @gayanper  Thanks for your great work! :) Sure I'll ask if there's anything to be clarified in #36.

**Comment by NipunaRanasinghe** [comment]
Closing in favor of #36.
