### ISSUE TITLE
Langauge server is not connected for all files

### ISSUE THREAD

**Issue by gayanper** [ballerina-platform/lsp4intellij#28]
**Steps to reproduce:**
1. Open a file which is connected to the language server
2. Close the file
After some time the green icon goes away from the status bar
3. Open the second file
Green icons is not shown.

Unfortunately i cannot test if the lang server is connected even though the green icon is not shown since symbols are not working and my lang server only provides symbols.

**Comment by NipunaRanasinghe** [comment]
I was able to reproduce this and will do a release within next week with the fix :)

**Comment by gayanper** [comment]
Any update on this issue ? if this is fixed i can continue my implementation with STS4 with configuration files.

**Comment by NipunaRanasinghe** [comment]
@gayanper Sorry for the late responses since I've been busy with our ballerina release. Could you please add the following jitpack build and verify if your issue is fixed?? :) 

`com.github.ballerina-platform:lsp4intellij:improved-inspections-SNAPSHOT`

**Comment by gayanper** [comment]
Unfortunately this branch doesn't have all the fixes i need like the language id support (The PR you merged from me). I will wait till you merge this to master.

**Comment by gayanper** [comment]
By the way i locally merged the master into this branch and tested out. Seems working fine for me.

**Comment by NipunaRanasinghe** [comment]
Okay then. I'll add the fix to the master. :+1:

**Comment by gayanper** [comment]
Well i found another scenario, where when opening the file if the server init timeout, It won't try to start the language server again regardless how many time i close and open the file. I have to restart the IDE to get the language server to try init again.

**Comment by gayanper** [comment]
> Well i found another scenario, where when opening the file if the server init timeout, It won't try to start the language server again regardless how many time i close and open the file. I have to restart the IDE to get the language server to try init again.

@NipunaRanasinghe i added a new small feature to get around the above problem https://github.com/ballerina-platform/lsp4intellij/pull/37

**Comment by NipunaRanasinghe** [comment]
@gayanper Thanks for working on it! I was thinking of a solution similar to `forced association` feature of the `lsp support` plugin. Lets add that later since it may need some more effort.
