### ISSUE TITLE
JitPack build broken

### ISSUE THREAD

**Issue by ctron** [ballerina-platform/lsp4intellij#297]
**Description:**

While it is really cool, it also seems broken:

https://jitpack.io/com/github/ballerina-platform/lsp4intellij/73af3920cc/build.log

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nixel2007** [comment]
Need to add jitpack cfg file to the root.
