### ISSUE TITLE
API to set different timeouts in the LSP client API

### ISSUE THREAD

**Issue by gayanper** [ballerina-platform/lsp4intellij#30]
**Description:**
Sometime the default timeout isn't enough for some language servers, it would be nice to change the timeouts, specially the init timeout. Some time the STS4 language server won't fully initialized in 10 seconds if the system is busy or if the project is a large project. So it would be nice to have a API to change this so the STS4 plugin for example can make it as a configuration in IDE settings for STS4 tooling.

**Comment by NipunaRanasinghe** [comment]
Yes indeed! This was already on our road map to the 1.0 release. :) Will improve API to change default timeouts.
