### ISSUE TITLE
[Bug] Leo plugin crashes Jetbrains products

### ISSUE THREAD

**Issue by iamalwaysuncomfortable** [ballerina-platform/lsp4intellij#306]
**Description:**
Leo activation of the LEO plugin causes Jetbrains IDEs to crash (cause will be investigated shortly) - likely do to an OOM error.

**Steps to reproduce:**
1. Download official LEO Plugin
2. Initialize it
3. View a .leo file
4. View a .rs rust language file
5. IDE Freezes

**Affected Versions:**
Jetbrains Leo Plugin 0.11.0 

**OS, DB, other environment details and versions:**
CLion 2022.3.2
Build #CL-223.8617.54, built on January 25, 2023
Licensed to Mike Turner
Subscription is active until February 28, 2023.
Runtime version: 17.0.5+1-b653.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2000M
Cores: 10
Metal Rendering is ON

**Comment by NipunaRanasinghe** [comment]
Closing as this issue, as it seems unrelated to the lsp4intellij client (and more like a plugin side error)
