### ISSUE TITLE
Add support for file name patterns 

### ISSUE THREAD

**Issue by gayanper** [ballerina-platform/lsp4intellij#32]
**Description:**
Today the implementation only support for file extensions. But in eclipse you could configure a full file name or filename patterns.
In STS4 context:
You can configuration the language server to use STS4 LS if the file name is such application*.properties

Now today the only way would be to bind the LS against extension .properties which makes the LS to connect on all java property files.

The suggestion is that to either introduce file type binding in IDEA to solve this or give priority to file name matching and if fails fallback to extension.

**Suggested Labels:**
Improvement

**Comment by NipunaRanasinghe** [comment]
I see your point.. If I got this right, if the user can provide their filename patterns as regex expressions instead of just file extensions, that would solve the issue right?? :)

**Comment by gayanper** [comment]
Yes that's correct 👍

**Comment by gayanper** [comment]
@NipunaRanasinghe here is a small experiment i did without changing much the way how server definitions are resolved. https://github.com/ballerina-platform/lsp4intellij/pull/38

I feel this is not fully perfect, but if we want a perfect solution we might need to rely heavily on IDEA file associations and base our server binding on that. That might be a huge change which i don't think worth trying to implementation right now.

**Comment by NipunaRanasinghe** [comment]
@gayanper Yeah I agree. I think we are all good with your way. I'll update the documentation when after the PR is merged :+1:

**Comment by NipunaRanasinghe** [comment]
@gayanper Shall we close since you have added this feature by #38?
