### ISSUE TITLE
Searching through forks to find fixes

### ISSUE THREAD

**Issue by payne911** [ballerina-platform/lsp4intellij#324]
Hey there,

I got curious and ran a scan against your repo: https://useful-forks.github.io/?repo=ballerina-platform/lsp4intellij

The results ended up being quite interesting:
![image](https://github.com/ballerina-platform/lsp4intellij/assets/38117856/976d0704-875a-419d-b2bb-766d40b78128)

And I think you may benefit from exploring a few of those commits to see if maybe you could cherry pick some fixes that may apply to the current sate of the codebase.

... that's it! I just thought I'd let you know. (Disclaimer: I actually maintain the `useful-forks` project.)

:)

**Comment by NipunaRanasinghe** [comment]
@payne911 Thanks for the suggestion! I went throug most of the forks and it seems there's not much of a gap w.r.t. this project. Hence closing for now.
