### ISSUE TITLE
When is the planned release date for the next version?

### ISSUE THREAD

**Issue by dongwa** [ballerina-platform/lsp4intellij#326]
We have stayed on version 0.95.1 for a long time, and there are many issues with it. Therefore, when is the planned release date for the next version?

**Comment by NipunaRanasinghe** [comment]
@dongwa Apologies for the delay cause got busy with few other priorities. Closing the issue as we've released 0.95.2 https://github.com/ballerina-platform/lsp4intellij/releases/tag/0.95.2.
