### ISSUE TITLE
Allow InitializeParams.ClientInfo to provide more info

### ISSUE THREAD

**Issue by payne911** [ballerina-platform/lsp4intellij#338]
We would like to use this structure which allows providing extra information about the client plugin:
```
data class MyClientInfo(
    val myName: String,
    val myVersion: String?,
    val extensionName: String?,
    val extensionVersion: String?
) : ClientInfo(myName, myVersion)
```

But we're not sure if there's already a way for us to actually change the `InitializeParams` structure being used.
Extending it doesn't seem to work because of `lsp4j`'s `InitializeParamsTypeAdapter` which would also need to be changed?

**Comment by nixel2007** [comment]
You could use initializationOptions in InitializeParams for that purpose.

**Comment by payne911** [comment]
Good point! Thanks
