### ISSUE TITLE
Error diagnostics and code actions not working properly

### ISSUE THREAD

**Issue by ThemiraChathumina** [ballerina-platform/lsp4intellij#353]
**Description:**
When an editor is opened, error diagnostics do not appear; they appear only after a change is made in the editor. If multiple editors are open simultaneously, error diagnostics are displayed only for the editor that was last changed. Additionally, when a code action is triggered, all error diagnostics disappear, and only the error messages related to the code action appear. Code actions that lack diagnostic context do not function. Also code action bulb do not appear in the 1st click. You need to change the caret position to trigger the code action bulb. 

**Examples:**

**Error annotations disappearing after a change is made in another editor.**

![20240410072040-ezgif com-video-to-gif-converter](https://github.com/ballerina-platform/lsp4intellij/assets/110608712/f5ba08fe-40d5-4dcf-a7c3-5fccd5e1d167)

**Error annotation disappearing after a code action is triggered.**

![20240410072127-ezgif com-video-to-gif-converter](https://github.com/ballerina-platform/lsp4intellij/assets/110608712/c9cd63cd-7454-4df7-8f31-ced21e622801)

**Comment by NipunaRanasinghe** [comment]
Closing as fixed with https://github.com/ballerina-platform/lsp4intellij/pull/354
