### ISSUE TITLE
Improve the hover content rendering

### ISSUE THREAD

**Issue by ThemiraChathumina** [ballerina-platform/lsp4intellij#356]
**Description:**

The current implementation does not add any styling or colors to the content displayed in the hover box. To enhance visual appeal, it would be beneficial to style the content within the hover box, such as highlighting the code, using an appropriate font, and adjusting the font size.

**Examples**

![image](https://github.com/ballerina-platform/lsp4intellij/assets/110608712/07d14c08-81e9-47c2-acc8-5352f81c1bb4)

![image](https://github.com/ballerina-platform/lsp4intellij/assets/110608712/0a229ea6-c9a1-487e-b1a4-bcde73be621b)

**Comment by NipunaRanasinghe** [comment]
Closing as fixed with https://github.com/ballerina-platform/lsp4intellij/pull/357
