### ISSUE TITLE
Parameter information is not shown in the signature help.

### ISSUE THREAD

**Issue by ThemiraChathumina** [ballerina-platform/lsp4intellij#360]
**Description:**
Parameter information is not displayed in the hover of signature help. 

Reproduced in Ballerina language server.
```
# Description.
#
# + x - parameter description
# + y - parameter description
# + return - return value description
function addInt2(int x, int y) returns int {
	return x + y;
}
```
![image](https://github.com/ballerina-platform/lsp4intellij/assets/110608712/272d577c-be46-4d9d-a8a5-0fbca7a607c7)

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/lsp4intellij/pull/361
