### ISSUE TITLE
Support for code actions resolve

### ISSUE THREAD

**Issue by ThemiraChathumina** [ballerina-platform/lsp4intellij#362]
**Description:**
The language server protocol feature that supports resolving code actions is not yet implemented. This feature will enable certain code actions that require more extensive computations.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/lsp4intellij/pull/363
