### ISSUE TITLE
Version 0.96.0 causes to slow down the IDE.

### ISSUE THREAD

**Issue by ThemiraChathumina** [ballerina-platform/lsp4intellij#364]
**Description:**
After upgrading to the latest version with the Ballerina language server, none of the features are working and the IDE is lagging. All requests are timing out. This issue is occurring in both IntelliJ 2023 and 2024 versions.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/lsp4intellij/pull/365
