### ISSUE TITLE
Some completion items do not show an icon.

### ISSUE THREAD

**Issue by ThemiraChathumina** [ballerina-platform/lsp4intellij#367]
**Description:**
$subject

![image](https://github.com/ballerina-platform/lsp4intellij/assets/110608712/a45434c2-9f4b-43e2-b500-27777453cd4a)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/lsp4intellij/pull/369
