### ISSUE TITLE
Hover content is not displaying properly in the Intellij new UI

### ISSUE THREAD

**Issue by ThemiraChathumina** [ballerina-platform/lsp4intellij#368]
**Description:**
Hover content is not taking the background color properly and it does not have a proper padding in intellij 2023 and 2024 versions new UI.

![image](https://github.com/ballerina-platform/lsp4intellij/assets/110608712/d023721f-0131-4aec-ad17-06d8a759717a)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/lsp4intellij/pull/369
