### ISSUE TITLE
Support for workspace/didChangeConfiguration

### ISSUE THREAD

**Issue by gayanper** [ballerina-platform/lsp4intellij#41]
Add support to send workspace/didChangeConfiguration after the language server is initialized. Implementing workspace/didChangeConfiguration is straight forward. But with the idea plugin we seems to missing a life-cycle hook which we can receive language server notification messages. May be we can send this once we receive the InitializeResult. But the consumer of this library don't have a way to hook into that phase. We need to come up with a mechanism to hook into this InitializeResult message the act on it.

**Comment by gayanper** [comment]
What if we add the support in ServerDefinition to provide a listener. By default there with be a noop listener. But consumer can plugin if he has one. We then call the listener when the initialization is done. The listener will also have default methods by design because that gives us the opportunity to add later new hooks without breaking backward compatibility. 
@nixel2007 and @NipunaRanasinghe what do you think about the suggested design ?

**Comment by gayanper** [comment]
I did some changes according my suggestion. Once tested i share my branch you can take look at it and see. Once things get into shape will make a PR. Sounds good ?

**Comment by NipunaRanasinghe** [comment]
@gayanper Thats great! Yeah please share your branch once the initial implementation is done and then we can work on optimizing the design (if required). Thanks for working on this :)

**Comment by rasika** [comment]
@gayanper this is a very good suggestion. I suppose client should notify through **workspace/didChangeConfiguration** for the initialization as well as per each config change.

**Comment by nixel2007** [comment]
Looks like I miss something. Why do you need any hook at server definition side? Why just not send regular request through existing intellij language client, as autocomplete or hover does?
My plugin - hey, I want to change config of my server. Hey, intellij client, post this config as didChangeConfiguration event via existing JSON RPC. Or all this talk with hooks about workspace/configuration event, server sends **to** client?

**Comment by gayanper** [comment]
@nixel2007 we need the support for listening server messages since, in my STS language server the initial configuration message need to sent as part of initialization after receiving InitializeResult as part of the ResponseMessage. After that we send the initialized message which will tell the server to use the configuration sent and start processing the code. Thats why we need the support for listening 🙂

**Comment by nixel2007** [comment]
@gayanper ah, I understand your needs now. So basicaly you need to subscribe to every response processing operation, not only workspace/configuration, right?

**Comment by gayanper** [comment]
Kind of yes, basically for sts4 we only need the InitializeResult. But we can easily add the rest as well.

**Comment by gayanper** [comment]
@nixel2007 @NipunaRanasinghe check this commit on my personal branch 
https://github.com/gayanper/lsp4intellij/commit/231f76a276a0b659f0f4863232ce0c9e5ab35236

**Comment by gayanper** [comment]
@rasika @NipunaRanasinghe what do you think about this implementation, if you are ok i can create a PR for this, for now i have added the `ServerListener` in `LanguageServiceDefinition` since i didn't want to force the consumer implementation extension just to send this message. But since the plan is to handle things through extensions, please let me know if we should add support for `ServerListener` through extension.

**Comment by gayanper** [comment]
This improvement must be fixed by https://github.com/ballerina-platform/lsp4intellij/pull/53. Shall we close this ?

**Comment by nixel2007** [comment]
@gayanper #53 is about initial configuration request, isn't it? what about another configuration request, invoked from client? does #52 provide a way to invoke it? could you provide small code example for it?

**Comment by gayanper** [comment]
@nixel2007 i think you can directly invoke `IntellijLanuageClient.didChangeConfiguration` or am i missing something ?

**Comment by nixel2007** [comment]
@gayanper looks like i've missed it somehow. thanks!

**Comment by NipunaRanasinghe** [comment]
@gayanper  Yeah we can close this now. Again, Thanks for your work!
