### ISSUE TITLE
Stop the possibility that requests can reach server before initialization

### ISSUE THREAD

**Issue by gayanper** [ballerina-platform/lsp4intellij#44]
When working with a LS implemented under spec version 3, the server expect to receive a InitializedParam request before any other request is made to server.

The current implementation of this library doesn't guarantee that.

**Comment by gayanper** [comment]
Should be fixed by https://github.com/ballerina-platform/lsp4intellij/pull/45

**Comment by NipunaRanasinghe** [comment]
Closing the issue since fixed by #45.
