### ISSUE TITLE
Show language server startup failure as an error in IDEA even log

### ISSUE THREAD

**Issue by gayanper** [ballerina-platform/lsp4intellij#47]
Today when the language server fail to start a message box is shown, this message box blocks the UI thread which makes all the dependent UI updates to wait till this message is dismissed, From a usability point of view show this message as a message box doesn't add value to end user interaction since user can only read and acknowledge it. In IDEA the way these kind of interaction are handled through the event log.

@NipunaRanasinghe @nixel2007 if you guys agree on this, i can start working on it.

**Comment by nixel2007** [comment]
Does Notification.Bus block UI thread? I send messages through it in my idea plugin, didn't notice any freezes

**Comment by gayanper** [comment]
@nixel2007 well swing is single threaded. So if you open a dialog you block all other UI operations other than the paint events triggered by swing. So basically if the ls is failed to startup while opening the editor. The editors styling and gutter icon rendering some time gets blocked because of this message box

**Comment by NipunaRanasinghe** [comment]
@gayanper yeah I think your suggestion will be better when considering from usability point of view as well. Let's move it to the idea event log.
