### ISSUE TITLE
EditorEventManager.java fail to compile with Intellij 2019 and run in Intellij 2019

### ISSUE THREAD

**Issue by gayanper** [ballerina-platform/lsp4intellij#54]
https://github.com/ballerina-platform/lsp4intellij/blob/9344b0631fa00c5ed151e4dae58a97c972568425/src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java#L520

The code at above line does not compile with IntelliJ 2019. The reason for that is the constructor has been changed since it is not a considered as part of the public API. Shouldn't we use the provided com.intellij.codeInsight.daemon.impl.LocalInspectionsPassFactory to create a instance ?

@NipunaRanasinghe @rasika

**Comment by gayanper** [comment]
What if we change the method like this ? i cannot test this since i don't have a language server plugin which has inspections

```java
    /**
     * Triggers local inspections for a given PSI file.
     */
    private void runInspection(PsiFile psiFile) {
        Document document = PsiDocumentManager.getInstance(project).getDocument(psiFile);
        if (document != null) {
            DumbService.getInstance(project).smartInvokeLater(() -> {
                TextEditorHighlightingPass localInspectionsPass = new LocalInspectionsPassFactory(
                    project, TextEditorHighlightingPassRegistrar
                    .getInstance(project)).createHighlightingPass(psiFile, editor);

                if (localInspectionsPass instanceof LocalInspectionsPass) {
                    ProgressManager.getInstance().runProcess(() -> {
                        ((LocalInspectionsPass) localInspectionsPass)
                            .doInspectInBatch(inspectionManagerEx.createNewGlobalContext(false), inspectionManagerEx,
                                inspectionToolWrapper);
                        UpdateHighlightersUtil
                            .setHighlightersToEditor(psiFile.getProject(), document, 0, document.getTextLength(),
                                localInspectionsPass.getInfos(), null, Pass.UPDATE_ALL);
                    }, new EmptyProgressIndicator());
                }
            });
        }
    }
```

**Comment by rasika** [comment]
+1 to use factory method. @NipunaRanasinghe shall we test this change?

**Comment by NipunaRanasinghe** [comment]
@gayanper @rasika +1 to use `LocalInspectionsPassFactory`. Lets proceed with it.. I'll verify with IDEA 2019.1 and send the PR. @gayanper Thanks for pointing this out! :)

**Comment by NipunaRanasinghe** [comment]
@gayanper I tried with the above suggestion but ended up with an assertion error when triggering inspections, as follows.

```
java.lang.AssertionError
	at com.intellij.codeInsight.daemon.impl.TextEditorHighlightingPassRegistrarImpl.registerTextEditorHighlightingPass(TextEditorHighlightingPassRegistrarImpl.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPassFactory.<init>(LocalInspectionsPassFactory.java:31)
	at org.wso2.lsp4intellij.editor.EditorEventManager.lambda$runInspection$9(EditorEventManager.java:523)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$7(DumbServiceImpl.java:445)
```
Am I doing something wrong?

**Comment by gayanper** [comment]
I checked the intelliJ source code and it seem we might need to take the factory from `project.getComponent(LocalInspectionsPassFactory.class)` that's how they have done for `ShowAutoImportPassFactory`  at https://sourcegraph.com/github.com/JetBrains/intellij-community@38dd8b9a8214fd577e0b4109c221e15cb55b24ae/-/blob/platform/lang-impl/src/com/intellij/codeInsight/daemon/impl/DefaultHighlightInfoProcessor.java?utm_source=share#L69:57

This is just a hunch so you may need to try it, also debug and see if a factory is already registered in the TextEditorHighlightingPassRegistrarImpl that might give us some hints and this https://www.jetbrains.org/intellij/sdk/docs/tutorials/code_inspections.html

**Comment by gayanper** [comment]
@NipunaRanasinghe hope the above information help you up to some extend. is it working now ?

**Comment by NipunaRanasinghe** [comment]
@gayanper Yeah it was very helpful indeed! :) I'll send the PR with revamped inspection implementation. Thanks!
