### ISSUE TITLE
New Timeout API doesn't work

### ISSUE THREAD

**Issue by gayanper** [ballerina-platform/lsp4intellij#56]
The timeouts which are added into `org.wso2.lsp4intellij.requests.Timeout#setTimeouts` doesn't reload the constants in the class. For example this cause the LanguageServerWrapper to use the old INIT timeout which it was initialized at the class loading time. 

IMO we should have the timeouts in the map than in constants, and read timeout through a getter method which will return the overridden one if exist or otherwise the default one.

https://github.com/ballerina-platform/lsp4intellij/blob/fab02d60fa8a7f26540e5bf47152ec81b1f7238d/src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java#L201

**Comment by gayanper** [comment]
@NipunaRanasinghe was this working with your language client ?

**Comment by NipunaRanasinghe** [comment]
@gayanper Seems I've missed to update those few places with the new change. :( I'll add the fix.
