### ISSUE TITLE
DefaultRequestManager#didChangeWatchedFiles is called from the wrong project

### ISSUE THREAD

**Issue by gayanper** [ballerina-platform/lsp4intellij#76]
To reproduce this,
1. Open a Intellij project A and open a file which is bound to a LS.
2. Open a another project B in a new window and open a file which is not bounded to the above LS or any other LS.

The project A language server receives a didChangeWatchedFiles request with the file from project B. This can cause problems in workspace symbols. We probably need to only loop and send this request to the project B LS wrappers. 

@NipunaRanasinghe @rasika i think the problem is at org.wso2.lsp4intellij.requests.FileEventManager#changedConfiguration(java.lang.String, org.eclipse.lsp4j.FileChangeType, org.wso2.lsp4intellij.client.languageserver.wrapper.LanguageServerWrapper) method which iterate over the all wrappers `IntellijLanguageClient.getAllServerWrappers()`

Should we change this ? Let me know may be i can work on this if you guys are busy.

**Comment by gayanper** [comment]
This may need to come from the place we create the LSWrapper. And also when looking up LSWrapper we need to pass in the ext and window project

**Comment by NipunaRanasinghe** [comment]
> This may need to come from the place we create the LSWrapper. And also when looking up LSWrapper we need to pass in the ext and window project

@gayanper  If so, I think we need to do a significant refactoring work right? Hopefully I'll be able to have a look by the next week since still working on a critical plugin feature. :)

**Comment by gayanper** [comment]
@NipunaRanasinghe i think the `extToLanguageWrapper` will keep the server wrapper against the project root URI and extension, so i think we might only have few areas to change, I will start looking into this then after i verify the completion changes you have done :).

**Comment by gayanper** [comment]
@NipunaRanasinghe i was able to fix this issue with few changes in 2-3 files. The only thing that worries me is that intellij lack a way to provide current projects that a virtualfile belongs to. So i had to write a intellij file index search to find that information. I will test my changes more to see if that search has any negative effect. If everything is fine i will create a PR so that we can discuss around it.

**Comment by gayanper** [comment]
@NipunaRanasinghe @rasika please check https://github.com/ballerina-platform/lsp4intellij/pull/77 and let me know your thoughts.

**Comment by NipunaRanasinghe** [comment]
Closing since fixed with #77.
