### ISSUE TITLE
[api improvement] add more components to ClientContext.

### ISSUE THREAD

**Issue by gayanper** [ballerina-platform/lsp4intellij#79]
When implementing customer LanguageClient implementations the need arises to access the current project this LanguageClient is serving and the instance of Requestmanager to use for contacting the language server.

Therefore the following must be expose through the LanguageClient's context
- Project
- RequestManager

**Comment by NipunaRanasinghe** [comment]
Closing since fixed by #80. @gayanper Thanks for working on this :)
