### ISSUE TITLE
[critical] Performance issue when typing due to inspections

### ISSUE THREAD

**Issue by gayanper** [ballerina-platform/lsp4intellij#83]
This a problem when the project is is a medium size project. This also cause multiple Sonar analysis jobs to be triggered as well since Sonar is part of the inspections

[snapshot-1558684648440.zip](https://github.com/ballerina-platform/lsp4intellij/files/3215729/snapshot-1558684648440.zip)

**Comment by gayanper** [comment]
@NipunaRanasinghe can we see if we can optimize this ?

**Comment by gayanper** [comment]
Fix is provided in https://github.com/ballerina-platform/lsp4intellij/pull/86

**Comment by NipunaRanasinghe** [comment]
Closing hence fixed by #86. @gayanper Thanks for your awsome work!
